name: Update GitHub Activity Graph

on:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight UTC
  workflow_dispatch:     # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README (force trigger re-render)
        run: |
          # Update README timestamp to force GitHub to refresh graph cache
          sed -i "s|<!--updated:.*-->|<!--updated: $(date '+%Y-%m-%d %H:%M:%S') -->|" README.md || echo "<!--updated: $(date '+%Y-%m-%d %H:%M:%S') -->" >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update activity graph timestamp" || exit 0
          git push
